name: auto-log-every-monday

on:
  # push:
  schedule: 
  # 1: minute (0-59)
  # 2: hour (0-23)
  # 3: day of month (1-31)
  # 4: month (1-12 or JAN-DEC)
  # 5: day of week (0-6 or SUN-SAT)
  # 使用的UTC时间
  # 北京时间=UTC + 8 => UTC = 北京时间 - 8
  # 每周一10:15（北京时间）执行一次
  - cron: '50 0 * * MON'

# jobs 是总的，可以包含多个工作流
jobs:

  # 工作流
  do-log:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    # uses 和 run 不能在一个步骤里
    # with 只能和 uses 配合使用

    - name: Run
      env:
        id: ${{ secrets.LOGIN_ID }}
        pwd: ${{ secrets.LOGIN_PWD }}
        cookie: ${{ secrets.LOGIN_COOKIE }}
        # 时区设置为上海
        TZ: Asia/Shanghai
      run: go run action/main.go -i $id -p $pwd -c $cookie

