name: Log Every Mon via Docker

on:
  schedule:
  - cron: '40 0 * * 1'
  
  workflow_dispatch:

jobs:
  docker-log:
    runs-on: ubuntu-latest
    steps:
      - name: Show time
        run: date
        
      - name: Show Timezone
        run: date -R
        
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch required Go modules
        run:  go mod download

      - name: Build
        run:  go build -v ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          build-args: |
            EDS_USR_ID=${{ secrets.LOGIN_ID }}
            EDS_USR_PWD=${{ secrets.LOGIN_PWD }}
          builder: ${{ steps.buildx.outputs.name }}
          push:    false
          load:    true
          tags: docker-eds-logger:latest
          no-cache: true

      - name: Run Container
        run: docker run docker-eds-logger
