name: Show Time

on:
  schedule:
  - cron: '40 0 * * *'
  
  workflow_dispatch:

jobs:
  show-time:
    strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Show time
        run: date
        
      - name: Show Timezone
        run: timedatectl

