name: Show Time

on:
  schedule:
  - cron: '0 8 * * *'
  
  workflow_dispatch:

jobs:
  show-time:
    runs-on: ubuntu-latest
    
    steps:
      - name: Show time
        run: date
        
      - name: Show Timezone
        run: timedatectl

