name: Show Time

on:
  schedule:
  - cron: '40 0 * * 1'
  
  workflow_dispatch:

jobs:
  docker-log:
    runs-on: ubuntu-latest
    steps:
      - name: Show time
        run: date
        
      - name: Show Timezone
        run: date -R

